### ISSUE TITLE
Fix naming of existentials

### ISSUE THREAD

**Issue by cryocz** [znx3p0/async_t#1]
Currently, `async_t` constructs names of associated existential types by taking the name of the function and appending `Fut`. Since the common naming scheme in Rust for functions is `lower_snake_case`, this leads to names with inconsistent naming (`foo_bar_bazFut` for example). This breaks the naming convention for associated types, which is `UpperCamelCase`, and prompts a compiler warning for the user (`#[warn(non_camel_case_types)]`). 

The name of the method should therefore be converted to the `UpperCamelCase` naming convention. This can be done by splitting on `_`, capitalizing every resulting item, and then concatenating the strings together to form a new name.

**Comment by znx3p0** [comment]
Tbh, I forgot about this crate since I quickly made it for a small project and was supposed to have more features (the original purpose was to have a `#[impl_trait]` macro that makes traits support existential types recursively (e.g. `-> Result<impl Display, impl Debug>`)
That way, this library could support async traits via juxtaposing `#[impl_trait]` and adding `impl Future<Output =ReturnType>` to async functions.
Atm the library is not that organized, but I'll rewrite it based on `#[impl_trait]` in the following days.

**Comment by znx3p0** [comment]
async trait now works based on impl trait, but using existential return types in async methods can return an ICE (I experienced this with three different methods, all gave up on ICE, will open up an issue about it). I'll upload it as soon as I finish testing it a bit.

**Comment by znx3p0** [comment]
the new version was has just been uploaded to crates.io
